version: "3.9"
services:
  loadbalancer:
    image: holappaj/loadbalancer:0.0
    container_name: loadbalancer
    network_mode: "host"
    ports:
      - 16432:16432

  chatserver:
    image: holappaj/chatserver:0.0
    container_name: chatserver
    network_mode: "host"
    depends_on:
      - loadbalancer
    ports:
      - 6969:6969

  gameserver1:
    image: holappaj/gameserver:0.4
    container_name: gameserver1
    network_mode: "host"
    depends_on:
      - loadbalancer
    ports:
      - 5050:5050

  gameserver2:
    image: holappaj/gameserver:0.4
    container_name: gameserver2
    network_mode: "host"
    depends_on:
      - loadbalancer
    ports:
      - 5051:5051

  # gameserver3:
  #   image: holappaj/gameserver:0.3
  #   container_name: gameserver3
  #   network_mode: "host"
  #   depends_on:
  #     - loadbalancer
  #   ports:
  #     - 5052:5052
